config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  get 'pages/team'

  get 'pages/advertise'

  get 'pages/contact'

  get 'pages/testimonial'

  get 'pages/magazine'

  get 'dashboards/index'

  resources :listings
  resources :hot_spots
  resources :distributions
  resources :cities
  resources :countries
  devise_for :admins
  
  scope :admins do
    root :to => 'dashboards#index', :as => :admin_root
  end
  
  root 'pages#index'

end

app/models/hot_spot.rb
class HotSpot < ActiveRecord::Base
    belongs_to :city
    has_many :listings
    
    accepts_nested_attributes_for :city
end

app/controllers/hot_spots_controller.rb
class HotSpotsController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :edit, :update, :destroy]
  before_action :set_hot_spot, only: [:show, :edit, :update, :destroy]

  # GET /hot_spots
  # GET /hot_spots.json
  def index
    #@hot_spots = HotSpot.all
    @city = City.all
    if params[:city].blank?
      @hot_spots = HotSpot.all
    else
      @city_id = City.find_by(name: params[:city]).id
      @hot_spots = HotSpot.where(city_id: @city_id).order("created_at DESC")
    end
  end

  # GET /hot_spots/1
  # GET /hot_spots/1.json
  def show
  end

  # GET /hot_spots/new
  def new
    @hot_spot = HotSpot.new
  end

  # GET /hot_spots/1/edit
  def edit
  end

  # POST /hot_spots
  # POST /hot_spots.json
  def create
    @hot_spot = HotSpot.new(hot_spot_params)

    respond_to do |format|
      if @hot_spot.save
        format.html { redirect_to @hot_spot, notice: 'Hot spot was successfully created.' }
        format.json { render :show, status: :created, location: @hot_spot }
      else
        format.html { render :new }
        format.json { render json: @hot_spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hot_spots/1
  # PATCH/PUT /hot_spots/1.json
  def update
    respond_to do |format|
      if @hot_spot.update(hot_spot_params)
        format.html { redirect_to @hot_spot, notice: 'Hot spot was successfully updated.' }
        format.json { render :show, status: :ok, location: @hot_spot }
      else
        format.html { render :edit }
        format.json { render json: @hot_spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hot_spots/1
  # DELETE /hot_spots/1.json
  def destroy
    @hot_spot.destroy
    respond_to do |format|
      format.html { redirect_to hot_spots_url, notice: 'Hot spot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hot_spot
      @hot_spot = HotSpot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hot_spot_params
      params.require(:hot_spot).permit(:name, :city_id)
    end
end

app/helpers/hot_spots_helper.rb
module HotSpotsHelper
end

app/views/hot_spots/_form.html.erb
<%= simple_form_for(@hot_spot) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :city, :include_blank => false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/hot_spots/edit.html.erb
<h1>Editing Hot Spot</h1>

<%= render 'form' %>

<%= link_to 'Show', @hot_spot %> |
<%= link_to 'Back', hot_spots_path %>

app/views/hot_spots/index.html.erb
<div class="row">
<% @hot_spots.all.each do |hot_spot| %>
  <div class="col-md-3" style="margin-top: 40px;">
    <h4 class="text-center"><%= link_to hot_spot.name, listings_path(hot_spot: hot_spot.name) %></h4>
    <% if admin_signed_in? %>
      <div class="row">
        <div class="col-sm-6">
          <%= link_to 'Edit', edit_hot_spot_path(hot_spot), class: "btn btn-warning form-control" %>
        </div>  
        <div class="col-sm-6">
          <%= link_to 'Delete', hot_spot, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger form-control" %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
</div>

app/views/hot_spots/new.html.erb
<h1>New Hot Spot</h1>

<%= render 'form' %>

<%= link_to 'Back', hot_spots_path %>

app/views/hot_spots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hot_spot.name %>
</p>

<%= link_to 'Edit', edit_hot_spot_path(@hot_spot) %> |
<%= link_to 'Back', hot_spots_path %>