config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  get 'pages/team'

  get 'pages/advertise'

  get 'pages/contact'

  get 'pages/testimonial'

  get 'pages/magazine'

  get 'dashboards/index'

  resources :listings
  resources :hot_spots
  resources :distributions
  resources :cities
  resources :countries
  devise_for :admins
  
  scope :admins do
    root :to => 'dashboards#index', :as => :admin_root
  end
  
  root 'pages#index'

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @countries = Country.all
    @cities = City.all
    @distributions = Distribution.all
    @hot_spots = HotSpot.all
    @listings = Listing.all
    @hash = Gmaps4rails.build_markers(@listings) do |listing, marker|
      marker.lat listing.latitude
      marker.lng listing.longitude
      marker.picture({
                      anchor: [0, 0],
                      url: "http://thecookiedining.com/mobimaps-pin.png",
                      width: "64",
                      height: "64"
                 })
    end
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/index.html.erb
<div class="row">
    <div class="col-md-12">
        <h1>Welcome admin</h1>        
    </div>
</div>
<hr>
<div class="row">
  <div class="col-md-12">
    <div style="width: 100%;">
      <div id="map" style='width: 100%; height: 400px;'></div>  
    </div>
  </div>
</div>
<hr>
<div class="row">
    <div class="col-md-3">
        <div class="panel panel-danger">
          <div class="panel-heading"><h3 class="text-center">Countries &amp; Cities</h2></div>
          <div class="panel-body">
              <div class="row">
                  <div class="col-sm-6">
                    <h5 class="text-center"><strong>Countries: <%= @countries.size %></strong></h5>          
                  </div>
                  <div class="col-sm-6">
                    <h5 class="text-center"><strong>Cities: <%= @cities.size %></strong></h5>          
                  </div>
              </div>
          </div>
          <div class="panel-footer">
              <div class="row">
                  <div class="col-sm-6">
                      <%= link_to 'Add Country', new_country_path, class: "btn btn-danger btn-block" %>
                  </div>
                  <div class="col-sm-6">
                      <%= link_to 'Add City', new_city_path, class: "btn btn-danger btn-block" %>
                  </div>
              </div>
          </div>
              
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-danger">
          <div class="panel-heading"><h3 class="text-center">Distributors</h2></div>
          <div class="panel-body">
            <h4 class="text-center"><strong>Total # of Distributors:</strong> <em><%= @distributions.size %></em></h4>

          </div>
          <div class="panel-footer"><%= link_to 'Add Distribution', new_distribution_path, class: "btn btn-danger btn-block" %></div>
        </div>
    </div>
    
    <div class="col-md-3">
        <div class="panel panel-danger">
          <div class="panel-heading"><h3 class="text-center">Hot Spot Categories</h2></div>
          <div class="panel-body">
            <h4 class="text-center"><strong>Total # of Categories:</strong> <em><%= @hot_spots.size %></em></h4>

          </div>
          <div class="panel-footer"><%= link_to 'Add Hot Spot Category', new_hot_spot_path, class: "btn btn-danger btn-block" %></div>
        </div>
    </div>
     
     <div class="col-md-3">
        <div class="panel panel-danger">
          <div class="panel-heading"><h3 class="text-center">Hot Spots</h2></div>
          <div class="panel-body">
            <h4 class="text-center"><strong>Total # of Hot Spots:</strong> <em><%= @listings.size %></em></h4>

          </div>
          <div class="panel-footer"><%= link_to 'Add Hot Spot', new_listing_path, class: "btn btn-danger btn-block" %></div>
        </div>
    </div>
    
</div>

<hr>


<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>