config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  get 'pages/team'

  get 'pages/advertise'

  get 'pages/contact'

  get 'pages/testimonial'

  get 'pages/magazine'

  get 'dashboards/index'

  resources :listings
  resources :hot_spots
  resources :distributions
  resources :cities
  resources :countries
  devise_for :admins
  
  scope :admins do
    root :to => 'dashboards#index', :as => :admin_root
  end
  
  root 'pages#index'

end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search a hot spot...">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if admin_signed_in? %>
          <li><%= link_to 'Home', dashboards_index_path %></li>
        <% else %>
          <li><%= link_to 'Home', root_path %></li>
        <% end %>
        <% if admin_signed_in? %>
          
          <li><%= link_to 'New Country', new_country_path %></li>
          <li><%= link_to 'New City', new_city_path %></li>
          <li><%= link_to 'New Hot Spot Category', new_hot_spot_path %></li>
          <li><%= link_to 'New Listing', new_listing_path %></li>
          <li><%= link_to('Logout', destroy_admin_session_path, :method => :delete) %></li>
        <% else %>
          <li>
            <%= link_to('Login', new_admin_session_path)  %>  
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore.js"></script>
  <script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>
<div class="container">
  <% flash.each do |type, message|  %>
		<div class="alert alert-info fade-in">
			<button class="close" data-dismiss="alert">x</button>
			<%= message %>
		</div>
	<% end %>
  <%= yield %>  
</div>


</body>
</html>